# Generated by Django 2.0.4 on 2018-04-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_cart_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='checked_out',
            new_name='cart_paid',
        ),
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
    ]
